import type { Metadata } from "next";
import { Changa_One } from "next/font/google"; // Import Changa One font
import "./globals.css";
import Navbar from "./component/Header/page";
import { UserProvider } from "@/context/UserContext";
import Footer from "./component/Footer/page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body > {/* Apply the Changa One font */}
        <UserProvider>
          <Navbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
